sonar.projectKey=temporal-rift_game-client
sonar.organization=temporal-rift

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.sourceEncoding=UTF-8
