declare global {
  interface Window {
    __APP_CONFIG__?: RuntimeConfig
  }
}

export interface AppConfig {
  readonly apiBaseUrl: string
  readonly oidcIssuerUrl: string
  readonly oidcClientId: string
  readonly oidcAudience: string
}

/**
 * Shape of `window.__APP_CONFIG__`, generated by the serving container's entrypoint from
 * environment variables at container start (see docker/render-runtime-config.sh) and loaded via a
 * classic `<script>` tag before the app bundle. Not Vite build-time env — this image is built once
 * and configured per environment at deploy time, not per build.
 */
export interface RuntimeConfig {
  readonly apiBaseUrl?: string
  readonly oidcIssuerUrl?: string
  readonly oidcClientId?: string
  readonly oidcAudience?: string
}

export type AppConfigResult =
  | { readonly ok: true; readonly config: AppConfig }
  | { readonly ok: false; readonly errors: readonly string[] }

function isAbsoluteHttpUrl(value: string): boolean {
  try {
    const url = new URL(value)
    return url.protocol === 'http:' || url.protocol === 'https:'
  } catch {
    return false
  }
}

/**
 * Validates the container-supplied runtime configuration before anything renders. Missing or
 * malformed values must surface as a recoverable configuration error rather than a crash or
 * invented default.
 */
export function resolveAppConfig(config: RuntimeConfig): AppConfigResult {
  const errors: string[] = []

  const apiBaseUrl = config.apiBaseUrl?.trim()
  if (!apiBaseUrl) {
    errors.push('apiBaseUrl is not configured.')
  } else if (!isAbsoluteHttpUrl(apiBaseUrl)) {
    errors.push('apiBaseUrl must be an absolute http(s) URL.')
  }

  const oidcIssuerUrl = config.oidcIssuerUrl?.trim()
  if (!oidcIssuerUrl) {
    errors.push('oidcIssuerUrl is not configured.')
  } else if (!isAbsoluteHttpUrl(oidcIssuerUrl)) {
    errors.push('oidcIssuerUrl must be an absolute http(s) URL.')
  }

  const oidcClientId = config.oidcClientId?.trim()
  if (!oidcClientId) {
    errors.push('oidcClientId is not configured.')
  }

  const oidcAudience = config.oidcAudience?.trim()
  if (!oidcAudience) {
    errors.push('oidcAudience is not configured.')
  }

  if (errors.length > 0) {
    return { ok: false, errors }
  }

  return {
    ok: true,
    config: {
      apiBaseUrl: apiBaseUrl!,
      oidcIssuerUrl: oidcIssuerUrl!,
      oidcClientId: oidcClientId!,
      oidcAudience: oidcAudience!,
    },
  }
}
