import * as z from 'zod'

declare global {
  interface Window {
    __APP_CONFIG__?: unknown
  }
}

export interface AppConfig {
  readonly apiBaseUrl: string
  readonly oidcIssuerUrl: string
  readonly oidcClientId: string
  readonly oidcAudience: string
}

function isAbsoluteHttpUrl(value: string): boolean {
  try {
    const url = new URL(value)
    return url.protocol === 'http:' || url.protocol === 'https:'
  } catch {
    return false
  }
}

// Every field reports its own readable message: a missing value and a malformed one are different
// fixes for whoever deploys the client. `abort` keeps a missing value from also reporting as malformed.
function configuredText(name: string) {
  return z
    .string({ error: `${name} is not configured.` })
    .trim()
    .min(1, { error: `${name} is not configured.`, abort: true })
}

function absoluteHttpUrl(name: string) {
  return configuredText(name).refine(isAbsoluteHttpUrl, { error: `${name} must be an absolute http(s) URL.` })
}

/**
 * Shape of `window.__APP_CONFIG__`, generated by the serving container's entrypoint from
 * environment variables at container start (see docker/render-runtime-config.sh) and loaded via a
 * classic `<script>` tag before the app bundle. Not Vite build-time env — this image is built once
 * and configured per environment at deploy time, not per build.
 */
export const runtimeConfigSchema = z.preprocess(
  // Anything but an object (a broken or missing config.js) reads as "nothing configured".
  (value) => (typeof value === 'object' && value !== null ? value : {}),
  z.object({
    apiBaseUrl: absoluteHttpUrl('apiBaseUrl'),
    oidcIssuerUrl: absoluteHttpUrl('oidcIssuerUrl'),
    oidcClientId: configuredText('oidcClientId'),
    oidcAudience: configuredText('oidcAudience'),
  }),
)

export type RuntimeConfig = Partial<Record<keyof AppConfig, unknown>>

export type AppConfigResult =
  | { readonly ok: true; readonly config: AppConfig }
  | { readonly ok: false; readonly errors: readonly string[] }

/**
 * Validates the container-supplied runtime configuration before anything renders. Missing or
 * malformed values must surface as a recoverable configuration error rather than a crash or
 * invented default.
 */
export function resolveAppConfig(config: unknown): AppConfigResult {
  const result = runtimeConfigSchema.safeParse(config)
  if (!result.success) {
    return { ok: false, errors: result.error.issues.map((issue) => issue.message) }
  }
  return { ok: true, config: result.data }
}
